# Generated by Django 3.0.4 on 2021-07-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTS', models.IntegerField()),
                ('F3GA', models.IntegerField()),
                ('F3GM', models.IntegerField()),
                ('F2GA', models.IntegerField()),
                ('F2GM', models.IntegerField()),
                ('FTA', models.IntegerField()),
                ('FTM', models.IntegerField()),
                ('ORB', models.IntegerField()),
                ('DRB', models.IntegerField()),
                ('TOV', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Four_Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PPP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('POSS', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eFG', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TOV_Percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ORB_Percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('FTR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_four_factors.BasicStat')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_four_factors.Team')),
            ],
        ),
        migrations.AddField(
            model_name='basicstat',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_four_factors.Team'),
        ),
    ]
