# Generated by Django 3.0.4 on 2021-07-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_four_factors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicstat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='four_factor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
